nome=input("Digite um funcionario: ")
empresa=input("Digite a instituição: ")
qtde_funcionarios=int(input("Digite a quantidade de funcionarios: "))
mediaMensalidade=float(input("Digite a média da mensalidade: "))
print("Possui: ", qtde_funcionarios, "funcionarios.")
print("A média da mensalidade é de: " + str(mediaMensalidade))
print("============ Verifique os tipos de dados abaixo ===============")
print("O tipo da variável [nome] é: ", type(nome))
print("O tipo da variável [empresa] é: ", type(empresa))
print("O tipo da variável [qtde_funcionarios] é: ", type(qtde_funcionarios))
print("O tipo da variável [mediaMensalidades] é: ", type(mediaMensalidade))